### ISSUE TITLE
Question: what are scripts commands in pubspec file ?

### ISSUE THREAD

**Issue by mohammadne** [Flutterando/Clean-Dart#14]
Hi.

sorry me for my questions.
because I don't know Portuguese, I can't watch your videos, and this is the source of questions.

what is :
```
scripts: 
    mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
    mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
```

what I did was to define some similar commands via aliases into my bash and use them,
but I don't know what is ```scripts``` in  ```pubspec```.

thanks

**Comment by Bwolfs2** [comment]
We are using a CLI called  [Slidy](https://github.com/Flutterando/slidy) to help us to Create Modules,pages and more others staffs, so with this we can run Custom Scripts... in this case mobx_build and mobx_watch is to run the command 'flutter pub run build_runner watch --delete-conflicting-outputs' just calling 'slidy run mobx_watch', if u are not using Mobx this can be useless for you =)

**Comment by mohammadne** [comment]
thanks, it is awesome

**Comment by Bwolfs2** [comment]
Other think that we are using is to create Flavors and Apk Builds like:
```  
scripts:
  dev: flutter run -d all --flavor dev -t lib/main_development.dart
  ho: flutter run -d all --flavor ho -t lib/main_staging.dart
  prod: flutter run -d all --flavor prod -t lib/main_production.dart
```

soh we can just run:  ```slidy run dev```
